// One-off dev-time script: culls unpopular/costly/impractical recipes from the
// already-fetched src/data/generatedRecipes.ts. Run after scripts/fetchMealDb.mjs:
//   node --experimental-strip-types scripts/curateRecipes.mjs
//
// Popularity: TheMealDB's free tier has no ratings/views data at all, so we do
// NOT attempt to model "popularity" — only the two objective, measurable signals
// below (per the user's explicit choice when asked).
//
// Cost: continuous per-serving ingredient cost (quantity/packageSize * price,
// NOT rounded up to whole packages) — rounding to a single serving's packages
// would unfairly punish any ingredient sold in a multi-serving pack, since real
// usage buys packages across a whole week's mealCount x servings, not one
// serving in isolation. This is purely a per-recipe quality bar, unrelated to
// the app's real shopping-list package rounding.
//
// Practicality: too many ingredients we can't price (unmappable to a real UK
// supermarket item) or just too many ingredients overall for a quick weekly
// meal are both signals a recipe is impractical for this app's purpose.
import { INGREDIENTS_BY_ID } from '../src/data/ingredients.ts';
import { TIER_MULTIPLIER } from '../src/data/constants.ts';

const COST_PER_SERVING_LIMIT = 5.0;
const UNMAPPED_INGREDIENTS_LIMIT = 3; // cull at 3+ unmapped ingredients
const TOTAL_INGREDIENTS_LIMIT = 18; // cull at >18 total ingredients (mapped + unmapped)

function unitPrice(ingredient) {
  return (ingredient.referencePriceGBP * TIER_MULTIPLIER.budget) / ingredient.packageSize;
}

function estimateContinuousCost(recipe) {
  let cost = 0;
  for (const ref of recipe.ingredients) {
    const ingredient = INGREDIENTS_BY_ID[ref.ingredientId];
    if (!ingredient || ingredient.isPantryItem) continue;
    cost += unitPrice(ingredient) * ref.quantity;
  }
  return cost;
}

function cullReason(recipe) {
  const cost = estimateContinuousCost(recipe);
  const unmapped = (recipe.unmappedIngredients ?? []).length;
  const totalIngredients = recipe.ingredients.length + unmapped;
  if (cost > COST_PER_SERVING_LIMIT) return `too expensive (£${cost.toFixed(2)}/serving)`;
  if (unmapped >= UNMAPPED_INGREDIENTS_LIMIT) return `too many unpriceable ingredients (${unmapped})`;
  if (totalIngredients > TOTAL_INGREDIENTS_LIMIT) return `too complex (${totalIngredients} ingredients)`;
  return null;
}

async function main() {
  const { GENERATED_RECIPES } = await import('../src/data/generatedRecipes.ts');

  const kept = [];
  const culled = [];
  for (const recipe of GENERATED_RECIPES) {
    const reason = cullReason(recipe);
    if (reason) culled.push({ name: recipe.name, cuisine: recipe.cuisine, reason });
    else kept.push(recipe);
  }

  console.log(`Kept ${kept.length} of ${GENERATED_RECIPES.length} recipes (culled ${culled.length}).\n`);
  console.log('Culled recipes:');
  for (const c of culled) console.log(`  [${c.cuisine}] ${c.name} — ${c.reason}`);

  const cuisineCounts = {};
  for (const r of kept) cuisineCounts[r.cuisine] = (cuisineCounts[r.cuisine] ?? 0) + 1;
  console.log('\nCuisine counts after curation:', cuisineCounts);

  const banner = `// AUTO-GENERATED by scripts/fetchMealDb.mjs + scripts/curateRecipes.mjs — do not hand-edit.
// Source: TheMealDB (https://www.themealdb.com). Recipe data & photos courtesy of TheMealDB.
// Culled for cost (>£${COST_PER_SERVING_LIMIT}/serving) and practicality (too many
// unpriceable or too many total ingredients) — see scripts/curateRecipes.mjs.
import type { Recipe } from '../types';

export const GENERATED_RECIPES: Recipe[] = ${JSON.stringify(kept, null, 2)};
`;

  const fs = await import('node:fs/promises');
  await fs.writeFile(new URL('../src/data/generatedRecipes.ts', import.meta.url), banner);
  console.log('\nWrote src/data/generatedRecipes.ts (curated)');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
