// Hand-curated TheMealDB ingredient-name -> our priced Ingredient id aliases.
// Keys are normalized (lowercase, trimmed) before lookup — see normalize() in fetchMealDb.mjs.
// More auditable than fuzzy matching at our ~140-ingredient scale.

const aliasGroups = {
  'chicken-breast': ['chicken breast', 'chicken breasts', 'chicken fillet', 'chicken fillets', 'boneless chicken breast', 'diced chicken', 'chicken cutlets'],
  'beef-mince': ['minced beef', 'beef mince', 'ground beef', 'lean beef mince', 'lean ground beef', 'beef', 'braising steak', 'stewing steak', 'beef chuck', 'beef brisket'],
  'beef-steak-rump': ['rump steak', 'rump steaks', 'steak', 'beef steak', 'skirt steak', 'flank steak'],
  'beef-steak-sirloin': ['sirloin steak', 'sirloin steaks', 'ribeye steak', 'fillet steak', 'beef fillet'],
  'pork-loin-steaks': ['pork chops', 'pork chop', 'pork loin', 'pork loin steaks', 'pork tenderloin', 'pork shoulder', 'pork belly', 'pork', 'ground pork', 'minced pork'],
  'sausages-pork': ['sausages', 'pork sausages', 'sausage', 'italian sausage', 'chorizo sausage'],
  'salmon-fillet': ['salmon', 'salmon fillet', 'salmon fillets', 'smoked salmon'],
  'white-fish-fillet': ['cod', 'cod fillet', 'cod fillets', 'haddock', 'white fish', 'white fish fillets', 'halibut', 'tilapia', 'sea bass', 'plaice'],
  'prawns-raw': ['prawns', 'shrimp', 'king prawns', 'raw prawns', 'jumbo shrimp'],
  eggs: ['eggs', 'egg', 'egg yolks', 'egg whites', 'large eggs', 'egg wash'],
  'tofu-firm': ['tofu', 'firm tofu', 'silken tofu'],
  halloumi: ['halloumi', 'halloumi cheese'],
  'chickpeas-canned': ['chickpeas', 'garbanzo beans', 'chick peas'],
  'lentils-red-dried': ['red lentils', 'lentils', 'green lentils', 'puy lentils'],
  'black-beans-canned': ['black beans'],
  'kidney-beans-canned': ['kidney beans', 'red kidney beans', 'dried white beans', 'white beans', 'cannellini beans', 'butter beans'],
  'lamb-mince': ['lamb mince', 'ground lamb', 'lamb', 'diced lamb', 'lamb shoulder', 'leg of lamb', 'lamb leg', 'lamb chops', 'goat meat', 'goat', 'beef shin'],
  'duck-breast': ['duck breast', 'duck breasts', 'duck'],
  'turkey-mince': ['turkey mince', 'ground turkey', 'turkey breast', 'turkey'],
  'tuna-tinned': ['tuna', 'canned tuna', 'tinned tuna', 'tuna steak'],
  chorizo: ['chorizo'],
  'bacon-streaky': ['bacon', 'streaky bacon', 'bacon rashers', 'smoked bacon', 'pancetta', 'ham'],
  'chicken-thighs': ['chicken thighs', 'chicken thigh', 'boneless chicken thighs', 'chicken drumsticks', 'chicken legs', 'whole chicken', 'chicken', 'chicken wings'],

  potatoes: ['potatoes', 'potato', 'new potatoes', 'baby potatoes', 'russet potatoes', 'russet potato', 'mashed potato'],
  'sweet-potato': ['sweet potato', 'sweet potatoes'],
  'rice-basmati': ['rice', 'basmati rice', 'long grain rice', 'white rice', 'jasmine rice', 'risotto rice', 'arborio rice', 'brown rice'],
  'pasta-penne': ['pasta', 'penne', 'penne pasta', 'fusilli', 'macaroni', 'farfalle'],
  spaghetti: ['spaghetti', 'linguine', 'tagliatelle'],
  'noodles-egg': ['egg noodles', 'noodles', 'stir-fry noodles'],
  'rice-noodles': ['rice noodles', 'vermicelli noodles', 'vermicelli'],
  'bread-loaf': ['bread', 'white bread', 'bread slices', 'bread loaf', 'baguette', 'brioche buns', 'burger buns', 'buns', 'crusty bread'],
  'tortilla-wraps': ['tortilla', 'tortillas', 'flour tortillas', 'wraps', 'corn tortillas'],
  couscous: ['couscous'],
  quinoa: ['quinoa'],
  'naan-bread': ['naan', 'naan bread'],
  gnocchi: ['gnocchi'],
  'oats-porridge': ['oats', 'porridge oats', 'rolled oats', 'oatmeal'],
  'plain-flour': ['flour', 'plain flour', 'all-purpose flour', 'all purpose flour', 'self-raising flour', 'self raising flour', 'wheat flour'],
  'puff-pastry': ['puff pastry', 'shortcrust pastry', 'pastry'],
  breadcrumbs: ['breadcrumbs', 'panko', 'panko breadcrumbs', 'dried breadcrumbs'],
  'pitta-bread': ['pitta bread', 'pita bread', 'pitta'],
  'bulgur-wheat': ['bulgur wheat', 'bulgur', 'cracked wheat'],

  'onions': ['onion', 'onions', 'red onion', 'white onion', 'yellow onion', 'shallot', 'shallots', 'challots', 'leek', 'leeks'],
  'garlic-bulb': ['garlic', 'garlic cloves', 'garlic clove', 'minced garlic', 'crushed garlic'],
  carrots: ['carrot', 'carrots', 'celery', 'swede', 'beetroot', 'fennel'],
  broccoli: ['broccoli'],
  'peppers-mixed': ['pepper', 'peppers', 'bell pepper', 'bell peppers', 'red pepper', 'green pepper', 'yellow pepper', 'red bell pepper', 'capsicum'],
  'tomatoes-fresh': ['tomato', 'tomatoes', 'cherry tomatoes', 'plum tomatoes', 'vine tomatoes'],
  'tinned-tomatoes': ['chopped tomatoes', 'tinned tomatoes', 'tinned tomatos', 'canned tomatoes', 'passata', 'crushed tomatoes', 'tomato sauce'],
  'spinach-bag': ['spinach', 'baby spinach', 'frozen spinach'],
  'mushrooms-chestnut': ['mushrooms', 'mushroom', 'chestnut mushrooms', 'button mushrooms', 'portobello mushrooms'],
  courgette: ['courgette', 'courgettes', 'zucchini'],
  aubergine: ['aubergine', 'eggplant', 'egg plants', 'egg plant'],
  cucumber: ['cucumber'],
  'salad-bag': ['lettuce', 'salad', 'mixed salad', 'salad leaves', 'iceberg lettuce', 'romaine lettuce'],
  'sweetcorn-tin': ['sweetcorn', 'corn', 'sweet corn', 'corn kernels'],
  'peas-frozen': ['peas', 'frozen peas', 'garden peas'],
  'green-beans': ['green beans', 'french beans'],
  cabbage: ['cabbage', 'red cabbage', 'white cabbage', 'beansprouts', 'bean sprouts'],
  'butternut-squash': ['butternut squash', 'squash', 'pumpkin'],
  avocado: ['avocado', 'avocados'],
  lime: ['lime', 'limes', 'lime juice', 'lime zest'],
  lemon: ['lemon', 'lemons', 'lemon juice', 'lemon zest'],
  'coriander-fresh': ['coriander', 'fresh coriander', 'cilantro'],
  'spring-onion': ['spring onion', 'spring onions', 'scallion', 'scallions', 'green onion'],
  'ginger-fresh': ['ginger', 'fresh ginger', 'root ginger', 'ground ginger'],
  'chilli-fresh': ['chilli', 'chili', 'red chilli', 'green chilli', 'chilli pepper', 'jalapeno', 'jalapenos', 'scotch bonnet', 'hotsauce', 'hot sauce'],
  bananas: ['banana', 'bananas'],
  'berries-mixed-frozen': ['mixed berries', 'blueberries', 'strawberries', 'raspberries', 'blackberries', 'raisins', 'dried apricots', 'sultanas'],
  apples: ['apple', 'apples', 'cooking apples'],
  oranges: ['orange', 'oranges', 'orange juice', 'orange zest'],
  'basil-fresh': ['basil', 'fresh basil'],
  'parsley-fresh': ['parsley', 'fresh parsley', 'flat leaf parsley', 'mint', 'fresh mint', 'mint leaves', 'dill', 'chives'],
  'black-olives': ['olives', 'black olives', 'green olives'],
  pesto: ['pesto', 'chimichurri sauce', 'chimichurri'],
  'salsa-jar': ['salsa'],
  'edamame-frozen': ['edamame'],

  'milk-semi-skimmed': ['milk', 'semi-skimmed milk', 'whole milk', 'skimmed milk', 'buttermilk', 'evaporated milk', 'condensed milk'],
  'cheddar-cheese': ['cheddar', 'cheddar cheese', 'grated cheese', 'cheese', 'gruyere', 'gruyre'],
  parmesan: ['parmesan', 'parmesan cheese', 'grated parmesan'],
  mozzarella: ['mozzarella', 'mozzarella cheese'],
  butter: ['butter', 'unsalted butter', 'salted butter', 'margarine', 'shortening'],
  'greek-yogurt': ['yogurt', 'greek yogurt', 'plain yogurt', 'natural yogurt'],
  'single-cream': ['cream', 'single cream', 'soured cream', 'sour cream', 'creme fraiche'],
  'double-cream': ['double cream', 'heavy cream', 'whipping cream'],
  'feta-cheese': ['feta', 'feta cheese'],
  'cream-cheese': ['cream cheese', 'philadelphia'],
  'coconut-milk-tin': ['coconut milk', 'coconut cream'],

  'peanut-butter': ['peanut butter'],
  tahini: ['tahini'],
  hummus: ['hummus'],
  'curry-paste': ['curry paste', 'madras curry paste', 'tikka paste', 'korma paste', 'curry powder blend', 'tamarind paste', 'tamarind'],
  'thai-curry-paste': ['thai green curry paste', 'thai red curry paste', 'green curry paste', 'red curry paste'],
  'harissa-paste': ['harissa', 'harissa paste', 'harissa spice'],
  'miso-paste': ['miso paste', 'miso'],

  'olive-oil': ['olive oil', 'extra virgin olive oil'],
  'vegetable-oil': ['vegetable oil', 'sunflower oil', 'oil', 'cooking oil', 'groundnut oil', 'canola oil', 'lard', 'sesame seed oil', 'rapeseed oil'],
  salt: ['salt', 'sea salt'],
  'black-pepper': ['black pepper', 'pepper (spice)', 'ground black pepper', 'salt and pepper'],
  paprika: ['paprika', 'smoked paprika'],
  cumin: ['cumin', 'ground cumin', 'cumin seeds', 'ground coriander', 'coriander seeds'],
  'chilli-flakes': ['chilli flakes', 'red pepper flakes', 'crushed red pepper', 'dried chilli'],
  'mixed-herbs': ['mixed herbs', 'dried herbs', 'italian herbs', 'herbes de provence', 'all-purpose seasoning', 'seasoning'],
  'garlic-powder': ['garlic powder', 'garlic salt'],
  'soy-sauce': ['soy sauce', 'dark soy sauce', 'light soy sauce', 'tamari'],
  'curry-powder': ['curry powder'],
  'stock-cube': ['stock cube', 'chicken stock cube', 'beef stock cube', 'vegetable stock cube', 'chicken stock', 'beef stock', 'vegetable stock', 'stock'],
  'tomato-puree': ['tomato puree', 'tomato paste'],
  mustard: ['mustard', 'dijon mustard', 'english mustard', 'mustard powder', 'wholegrain mustard'],
  vinegar: ['vinegar', 'white wine vinegar', 'red wine vinegar', 'balsamic vinegar', 'malt vinegar', 'cider vinegar', 'apple cider vinegar'],
  honey: ['honey'],
  'sesame-seeds': ['sesame seeds', 'sesame oil'],
  'oyster-sauce': ['oyster sauce'],
  'fish-sauce': ['fish sauce'],
  'rice-vinegar': ['rice vinegar', 'rice wine vinegar', 'rice wine'],
  'caster-sugar': ['sugar', 'caster sugar', 'granulated sugar', 'icing sugar', 'powdered sugar'],
  'brown-sugar': ['brown sugar', 'demerara sugar', 'muscovado sugar'],
  'vanilla-extract': ['vanilla extract', 'vanilla essence', 'vanilla pod'],
  cinnamon: ['cinnamon', 'ground cinnamon', 'cinnamon stick'],
  'baking-powder': ['baking powder', 'baking soda', 'bicarbonate of soda', 'yeast'],
  cornflour: ['cornflour', 'cornstarch', 'corn starch', 'corn flour', 'starch'],
  'worcestershire-sauce': ['worcestershire sauce'],
  mayonnaise: ['mayonnaise', 'mayo'],
  ketchup: ['ketchup', 'tomato ketchup', 'bbq sauce', 'barbecue sauce'],
  'bay-leaves': ['bay leaves', 'bay leaf'],
  'dried-thyme': ['thyme', 'dried thyme', 'fresh thyme', 'rosemary', 'dried rosemary'],
  'dried-oregano': ['oregano', 'dried oregano', 'marjoram'],
  turmeric: ['turmeric', 'turmeric powder', 'ground turmeric'],
  'garam-masala': ['garam masala'],
  allspice: ['allspice'],
  cloves: ['cloves', 'ground cloves'],
  cardamom: ['cardamom', 'cardamom pods', 'ground cardamom', 'star anise', 'saffron'],
  'cooking-wine': ['red wine', 'white wine', 'dry sherry', 'sherry', 'sherry vinegar', 'palm sugar', 'wine', 'dry white wine'],
  nutmeg: ['nutmeg', 'ground nutmeg'],
  'chilli-powder': ['chilli powder', 'chili powder', 'cayenne pepper', 'cayenne'],
  'mixed-nuts': ['nuts', 'almonds', 'walnuts', 'cashews', 'pine nuts', 'peanuts', 'pecans', 'hazelnuts', 'flaked almonds'],
  'desiccated-coconut': ['desiccated coconut', 'shredded coconut', 'coconut flakes'],
  capers: ['capers', 'anchovies', 'anchovy'],
  gherkins: ['gherkins', 'pickles', 'pickle'],
};

export const MEALDB_INGREDIENT_ALIASES = Object.fromEntries(
  Object.entries(aliasGroups).flatMap(([ingredientId, names]) => names.map((name) => [name, ingredientId])),
);
